#!/usr/bin/env python

VER_NUM = "0.2.0"

import sys
import time
import db
import ui
import config

print "Records Project Paper Augmentation System, version " + VER_NUM
print "Copyright (c) 2014 Soren Bjornstad. See COPYING for license details."
time.sleep(0.5)
#if config.IS_PRODUCTION:
#    print "Warning: This is a PRODUCTION database!"
#    raw_input("(Press Return to start program)")
#else:
#    print "This is a TEST database."

ui.main.screen()
